### ISSUE TITLE
How to get foot height trajectory by hpp-walkgen?

### ISSUE THREAD

**Issue by longwoo** [humanoid-path-planner/hpp-walkgen#3]
According to the demo ```twenty-steps.cc ``` in the project tests file, we can get the trajectory (t,x,y) of com and (t,x,y) of left and right foot by giving the height of com and  a sequence of footprint.

However, more information need to know for example the sequence of foot height and orientation if we want to calculate joint position of legs. It seems hpp-walkgen doesn't support this or I misunderstand it ?

**Comment by jmirabel** [comment]
The trajectory of the foot are computed using class `Step` in `foot-trajectory.hh`, given two foot prints and two heights (height of the floor and highest height reached by the foot). See `SplineBased::defaultStepHeight`.

The joint parameters are then computed using numerical inverse kinematic. Constraint resolution is at the core of the HPP software.

**Comment by longwoo** [comment]
Thank you. It works.
